feat: add unregister snap name logic
canonical/snapcraft.io pull request #4670
Opened 2024-06-03 05:44 UTC by abbiesims

## Done
Adds Unregister snap name logic to `/snaps` page and to the Settings tab of a registered snap.

## How to QA
***If you have no registered snap names, check the videos below.***

Otherwise:
1. If you have a registered snap name that you have not published, go to `/snaps` and try to unregister it.
2. Go to the Settings tab of a registered snap name and unregister from here.

## Testing
- [X] This PR has tests
- [ ] No testing required (explain why):

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-6771

## Screenshots
Successfully unregister a snap name from `/snaps`:
[Screencast from 03-06-24 09:23:57.webm](https://github.com/canonical/snapcraft.io/assets/74302970/577969c6-5238-42f8-ae00-61bbc3b65152)
Error when unregistering from `/snaps` as I am not a publisher:
[Screencast from 03-06-24 09:24:15.webm](https://github.com/canonical/snapcraft.io/assets/74302970/90656ff9-81e6-42e4-b172-c3b7d8627fb4)
Successfully unregister a snap name from Settings tab, and reload page to `/snaps`
[Screencast from 03-06-24 09:24:45.webm](https://github.com/canonical/snapcraft.io/assets/74302970/81e8bea1-a5db-49df-b265-fd1669053706)
Error when unregistering from Settings tab as I am not a publisher:
[Screencast from 03-06-24 09:25:34.webm](https://github.com/canonical/snapcraft.io/assets/74302970/c27b30a7-0a06-4e44-9cc5-1fdf603503d4)

2024-06-03 05:44 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://snapcraft-io-4670.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/14914)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-03 08:08 UTC, steverydz requested changes
All looks good but I'd suggest using `user-event` rather than the built-in `fireEvent` as it is more representative of what happens when a user interacts with the page.

An example: https://github.com/canonical/snapcraft.io/blob/a0b128fa24b670b196acdd6197ca05ffc5499b5b/static/js/store/pages/Packages/__tests__/Packages.test.tsx#L4

Docs: https://testing-library.com/docs/user-event/v13/

2024-06-04 13:15 UTC, steverydz approved these changes
LGTM 👍

2024-06-04 13:49 UTC, AnnSoMuller commented
Good! 
I would just suggest to keep "Publish to this name" as link buttons
https://vanillaframework.io/docs/patterns/buttons

2024-06-04 14:02 UTC, merged